/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test03;

import javax.swing.JOptionPane;

/**
 *
 * @author christoftobias.weick
 */
public class NotenrechnerForm extends javax.swing.JFrame {

    /**
     * Creates new form NotenrechnerForm
     */
    public NotenrechnerForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundButtonGroup = new javax.swing.ButtonGroup();
        panelTitle = new javax.swing.JLabel();
        inputSubpanel = new javax.swing.JPanel();
        roundtenth = new javax.swing.JRadioButton();
        roundhalf = new javax.swing.JRadioButton();
        roundTitle = new javax.swing.JLabel();
        maxpoints = new javax.swing.JSpinner();
        maxPointslabel = new javax.swing.JLabel();
        myPointlabel = new javax.swing.JLabel();
        mypoints = new javax.swing.JTextField();
        tocalc = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        outputsubpanel = new javax.swing.JPanel();
        mygradelabel = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        myname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTitle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        panelTitle.setText("Prüfung 03 / Notenrechner");

        inputSubpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        roundButtonGroup.add(roundtenth);
        roundtenth.setSelected(true);
        roundtenth.setText("Zehntels Noten");
        roundtenth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundtenthActionPerformed(evt);
            }
        });

        roundButtonGroup.add(roundhalf);
        roundhalf.setText("Halbe Noten");
        roundhalf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundhalfActionPerformed(evt);
            }
        });

        roundTitle.setText("Rundung");

        maxpoints.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        maxPointslabel.setText("Max Punkte");

        myPointlabel.setText("Meine Punkte");

        mypoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mypointsActionPerformed(evt);
            }
        });

        tocalc.setText("berechne");
        tocalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tocalcActionPerformed(evt);
            }
        });

        reset.setText("reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputSubpanelLayout = new javax.swing.GroupLayout(inputSubpanel);
        inputSubpanel.setLayout(inputSubpanelLayout);
        inputSubpanelLayout.setHorizontalGroup(
            inputSubpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputSubpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputSubpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundTitle)
                    .addGroup(inputSubpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(roundtenth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roundhalf))
                    .addGroup(inputSubpanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(inputSubpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxPointslabel)
                            .addComponent(myPointlabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(inputSubpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mypoints, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxpoints, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputSubpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tocalc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reset)
                .addContainerGap())
        );
        inputSubpanelLayout.setVerticalGroup(
            inputSubpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputSubpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundTitle)
                .addGap(11, 11, 11)
                .addGroup(inputSubpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roundtenth)
                    .addComponent(roundhalf))
                .addGap(38, 38, 38)
                .addGroup(inputSubpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxpoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxPointslabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputSubpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mypoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myPointlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(inputSubpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tocalc)
                    .addComponent(reset))
                .addContainerGap())
        );

        outputsubpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mygradelabel.setText("Meine Note:");

        javax.swing.GroupLayout outputsubpanelLayout = new javax.swing.GroupLayout(outputsubpanel);
        outputsubpanel.setLayout(outputsubpanelLayout);
        outputsubpanelLayout.setHorizontalGroup(
            outputsubpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputsubpanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(mygradelabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        outputsubpanelLayout.setVerticalGroup(
            outputsubpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputsubpanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(mygradelabel)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        exit.setText("exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        myname.setText("Christof Weickhardt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelTitle)
                            .addComponent(inputSubpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(outputsubpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(myname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputSubpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputsubpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(myname))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roundtenthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundtenthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundtenthActionPerformed

    private void roundhalfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundhalfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundhalfActionPerformed

    private void mypointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mypointsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mypointsActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void tocalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tocalcActionPerformed
        int max = (int)this.maxpoints.getValue();
        double my = 0;
        try{
            my = new Double(this.mypoints.getText());
        }catch(Exception e){
            if(this.mypoints.getText().isEmpty() && (roundhalf.isSelected()||roundtenth.isSelected()) && maxpoints.getValue() != null){
                JOptionPane.showMessageDialog(this,"Haben Sie alles ausgefüllt?","Warnung",JOptionPane.INFORMATION_MESSAGE);
                return;
            }else{
                JOptionPane.showMessageDialog(this,"Das eingegebene ist keine Zahl","Fehler",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        double grade = (my*5)/max+1;
        if(my > max){
            JOptionPane.showMessageDialog(this, "erreichte Punkte übersteigt max Punkte", "Fehler", JOptionPane.ERROR_MESSAGE);
        }else{
             if(roundhalf.isSelected()){
                double roundedgrade = ((int)(2*(grade+0.25)))/2.0;
                mygradelabel.setText("Meine Note: "+roundedgrade);
             }else{
                double roundedgrade = ((int)(10*(grade+0.05)))/10.0;
                mygradelabel.setText("Meine Note: "+roundedgrade);
             }  
        }
    }//GEN-LAST:event_tocalcActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        maxpoints.setValue(0);
        mypoints.setText("");
        roundButtonGroup.clearSelection();
        mygradelabel.setText("Meine Note:");
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotenrechnerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotenrechnerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotenrechnerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotenrechnerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotenrechnerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JPanel inputSubpanel;
    private javax.swing.JLabel maxPointslabel;
    private javax.swing.JSpinner maxpoints;
    private javax.swing.JLabel myPointlabel;
    private javax.swing.JLabel mygradelabel;
    private javax.swing.JLabel myname;
    private javax.swing.JTextField mypoints;
    private javax.swing.JPanel outputsubpanel;
    private javax.swing.JLabel panelTitle;
    private javax.swing.JButton reset;
    private javax.swing.ButtonGroup roundButtonGroup;
    private javax.swing.JLabel roundTitle;
    private javax.swing.JRadioButton roundhalf;
    private javax.swing.JRadioButton roundtenth;
    private javax.swing.JButton tocalc;
    // End of variables declaration//GEN-END:variables
}
